### PR TITLE
fix: attributes support

### LINKED ISSUE #51: Parse PHP attributes
Parse [PHP attributes](https://www.php.net/manual/en/language.attributes.overview.php).

See test cases: https://github.com/nikic/PHP-Parser/blob/master/test/code/parser/stmt/attributes.test

### PR DESCRIPTION
**Pull request by azjezz**
~this handles attributes everywhere except one specific case:~

```php
$e = new #[Foo] class {}
```

~fix for anonymous classes will be in another PR.~

attributes are now supported everywhere: functions, parameters, properties, classes, interfaces, traits, enums, anonymous functions, arrow functions, and anonymous classes.

closes #51

### CODE REVIEW

File: src/parser/state.rs [hunk 1]
```diff
@@ -145,9 +160,11 @@ impl State {
...
 
     pub fn clear_comments(&mut self) -> Vec<Token> {
-        let c = self.comments.clone();
-        self.comments = vec![];
-        c
+        let mut comments = vec![];
+
+        std::mem::swap(&mut self.comments, &mut comments);
+
+        comments
```
Comment (azjezz) [inline src/parser/state.rs:167]: this is more efficient than cloning.

File: src/parser/ast.rs [hunk 2]
```diff
@@ -304,6 +307,12 @@ pub enum TraitAdaptation {
     },
 }
 
+#[derive(Debug, PartialEq, Clone)]
+pub struct Attribute {
+    pub span: Span,
```
Comment (azjezz) [inline src/parser/ast.rs:312]: we don't do this for other nodes, but we should start doing it.

File: src/parser/internal/attributes.rs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+                state.next();
+            } else {
+                break;
+            }
+        }
+
+        self.rbracket(state)?;
+
+        // recursive, looking for multiple attribute brackets after each other.
+        self.gather_attributes(state).map(|_| true)
```
Comment (azjezz) [inline src/parser/internal/attributes.rs:34]: this basically looks for code like this:

```php
#[Entity]
#[Validated]
class User {}
```

the initial function call will only collect `Entity`, so we call again to collect `Validated`, third call will not find `#[` and return.

File: src/parser/internal/classish.rs [hunk 4]
```diff
@@ -90,6 +93,8 @@ impl Parser {
 
             self.lbrace(state)?;
 
+            let attributes = state.get_attributes();
```
Comment (azjezz) [inline src/parser/internal/classish.rs:96]: this is important, if we don't call `get_attributes` before parsing the body, the attributes might end up on a member instead of the trait/class/enum/interface.

File: src/parser/error.rs [hunk 5]
```diff
@@ -82,6 +83,7 @@ impl Display for ParseError {
             Self::ForbiddenTypeUsedInProperty(class, prop, ty, span) => write!(f, "Parse Error: Property {}::${} cannot have type `{}` on line {} column {}", class, prop, ty, span.0, span.1),
             Self::MatchExpressionWithMultipleDefaultArms(span) => write!(f, "Parse Error: Match expressions may only contain one default arm on line {} column {}", span.0, span.1),
             Self::CannotFindTypeInCurrentScope(ty, span) => write!(f, "Parse Error: Cannot find type `{}` in this scope on line {} on column {}", ty, span.0, span.1),
+            Self::ExpectedItemDefinitionAfterAttributes(span) => write!(f, "Parse Error: Expected item definition after attribute on line {} column {}", span.0, span.1),
```
Comment (azjezz) [inline src/parser/error.rs:86]: this is the same as the rust error message for when an attribute exists with no item after it, it is different from PHP which is a generic `unexpected token` error message.

i believe the rust error message is more understandable in this case.

File: src/parser/ast.rs (hunk 2 above)
Comment (ryangjchandler) [reply src/parser/ast.rs:312]: Yeah, having some sort of `meta` property that contains the span, and any other info would be useful. Comments perhaps

**Review by ryangjchandler — APPROVED** [review]
